apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config

data:
  # Search for values inside `envs` on helm/hello-world/values.yaml
  {{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}