apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secrets
type: Opaque
stringData:
# Search for values inside `secretEnvs` on helm/hello-world/values.yaml
# Automatically converts secret string to base64 format
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: "{{ $value }}"
{{- end }}